package dao;

import java.util.List;

import entity.Indexes;

public interface IndexesMapper {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int insert(Indexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int insertSelective(Indexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    Indexes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int updateByPrimaryKeySelective(Indexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int updateByPrimaryKey(Indexes record);
    /**
     * 获取一级检索索引,indexclass=1
     * @author ss
     * @date 2018-3-25
     */
    List<Indexes> getFirstClassIndex();
    /**
     * 获取二级检索索引,indexclass=2
     * @author lk
     * @date 2018-3-25
     */
    List<Indexes> getSecondClassIndex();
}