package dao;

import entity.Indexes;

public interface IndexesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int insert(Indexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int insertSelective(Indexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    Indexes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int updateByPrimaryKeySelective(Indexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int updateByPrimaryKey(Indexes record);
}