package dao;

import entity.Usertocompany;

public interface UsertocompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertocompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertocompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int insert(Usertocompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertocompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int insertSelective(Usertocompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertocompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    Usertocompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertocompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int updateByPrimaryKeySelective(Usertocompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertocompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int updateByPrimaryKey(Usertocompany record);
}