package dao;

import entity.Usertoindex;

public interface UsertoindexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertoindex
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertoindex
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int insert(Usertoindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertoindex
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int insertSelective(Usertoindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertoindex
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    Usertoindex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertoindex
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int updateByPrimaryKeySelective(Usertoindex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertoindex
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    int updateByPrimaryKey(Usertoindex record);
}