package entity;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.areainfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String areainfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.areainfo
     *
     * @return the value of area.areainfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getAreainfo() {
        return areainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.areainfo
     *
     * @param areainfo the value for area.areainfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setAreainfo(String areainfo) {
        this.areainfo = areainfo == null ? null : areainfo.trim();
    }
}