package entity;

public class Companytoindex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companytoindex.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companytoindex.idindexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer idindexes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companytoindex.idcompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer idcompany;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companytoindex.id
     *
     * @return the value of companytoindex.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companytoindex.id
     *
     * @param id the value for companytoindex.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companytoindex.idindexes
     *
     * @return the value of companytoindex.idindexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIdindexes() {
        return idindexes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companytoindex.idindexes
     *
     * @param idindexes the value for companytoindex.idindexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIdindexes(Integer idindexes) {
        this.idindexes = idindexes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companytoindex.idcompany
     *
     * @return the value of companytoindex.idcompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIdcompany() {
        return idcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companytoindex.idcompany
     *
     * @param idcompany the value for companytoindex.idcompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIdcompany(Integer idcompany) {
        this.idcompany = idcompany;
    }
}