package entity;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyname
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyemail
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String companyemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.idarea
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer idarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String companyinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyname
     *
     * @return the value of company.companyname
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyname
     *
     * @param companyname the value for company.companyname
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyemail
     *
     * @return the value of company.companyemail
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getCompanyemail() {
        return companyemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyemail
     *
     * @param companyemail the value for company.companyemail
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setCompanyemail(String companyemail) {
        this.companyemail = companyemail == null ? null : companyemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.idarea
     *
     * @return the value of company.idarea
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIdarea() {
        return idarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.idarea
     *
     * @param idarea the value for company.idarea
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIdarea(Integer idarea) {
        this.idarea = idarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyinfo
     *
     * @return the value of company.companyinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getCompanyinfo() {
        return companyinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyinfo
     *
     * @param companyinfo the value for company.companyinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setCompanyinfo(String companyinfo) {
        this.companyinfo = companyinfo == null ? null : companyinfo.trim();
    }
}