package entity;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gradeinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String gradeinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gradeinfo
     *
     * @return the value of grade.gradeinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getGradeinfo() {
        return gradeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gradeinfo
     *
     * @param gradeinfo the value for grade.gradeinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setGradeinfo(String gradeinfo) {
        this.gradeinfo = gradeinfo == null ? null : gradeinfo.trim();
    }
}