package entity;

public class Indexes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indexes.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indexes.indexinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String indexinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indexes.taglevel
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer taglevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indexes.indexclass
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer indexclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indexes.parent
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indexes.id
     *
     * @return the value of indexes.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indexes.id
     *
     * @param id the value for indexes.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indexes.indexinfo
     *
     * @return the value of indexes.indexinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getIndexinfo() {
        return indexinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indexes.indexinfo
     *
     * @param indexinfo the value for indexes.indexinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIndexinfo(String indexinfo) {
        this.indexinfo = indexinfo == null ? null : indexinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indexes.taglevel
     *
     * @return the value of indexes.taglevel
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getTaglevel() {
        return taglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indexes.taglevel
     *
     * @param taglevel the value for indexes.taglevel
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setTaglevel(Integer taglevel) {
        this.taglevel = taglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indexes.indexclass
     *
     * @return the value of indexes.indexclass
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIndexclass() {
        return indexclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indexes.indexclass
     *
     * @param indexclass the value for indexes.indexclass
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIndexclass(Integer indexclass) {
        this.indexclass = indexclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indexes.parent
     *
     * @return the value of indexes.parent
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indexes.parent
     *
     * @param parent the value for indexes.parent
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }
}