package entity;

public class Originaldata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column originaldata.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column originaldata.companyname
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column originaldata.idarea
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer idarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column originaldata.companyemail
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String companyemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column originaldata.otherinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String otherinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column originaldata.companyinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private String companyinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column originaldata.id
     *
     * @return the value of originaldata.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column originaldata.id
     *
     * @param id the value for originaldata.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column originaldata.companyname
     *
     * @return the value of originaldata.companyname
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column originaldata.companyname
     *
     * @param companyname the value for originaldata.companyname
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column originaldata.idarea
     *
     * @return the value of originaldata.idarea
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIdarea() {
        return idarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column originaldata.idarea
     *
     * @param idarea the value for originaldata.idarea
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIdarea(Integer idarea) {
        this.idarea = idarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column originaldata.companyemail
     *
     * @return the value of originaldata.companyemail
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getCompanyemail() {
        return companyemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column originaldata.companyemail
     *
     * @param companyemail the value for originaldata.companyemail
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setCompanyemail(String companyemail) {
        this.companyemail = companyemail == null ? null : companyemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column originaldata.otherinfo
     *
     * @return the value of originaldata.otherinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getOtherinfo() {
        return otherinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column originaldata.otherinfo
     *
     * @param otherinfo the value for originaldata.otherinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setOtherinfo(String otherinfo) {
        this.otherinfo = otherinfo == null ? null : otherinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column originaldata.companyinfo
     *
     * @return the value of originaldata.companyinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public String getCompanyinfo() {
        return companyinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column originaldata.companyinfo
     *
     * @param companyinfo the value for originaldata.companyinfo
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setCompanyinfo(String companyinfo) {
        this.companyinfo = companyinfo == null ? null : companyinfo.trim();
    }
}