package entity;

public class Usertocompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertocompany.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertocompany.iduser
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertocompany.idcompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer idcompany;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertocompany.id
     *
     * @return the value of usertocompany.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertocompany.id
     *
     * @param id the value for usertocompany.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertocompany.iduser
     *
     * @return the value of usertocompany.iduser
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertocompany.iduser
     *
     * @param iduser the value for usertocompany.iduser
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertocompany.idcompany
     *
     * @return the value of usertocompany.idcompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIdcompany() {
        return idcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertocompany.idcompany
     *
     * @param idcompany the value for usertocompany.idcompany
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIdcompany(Integer idcompany) {
        this.idcompany = idcompany;
    }
}