package entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userID
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userlevel
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private Integer userlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.picture
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.idarea
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private Integer idarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.idgrade
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    private Integer idgrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userID
     *
     * @return the value of user.userID
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userID
     *
     * @param userid the value for user.userID
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel
     *
     * @return the value of user.tel
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel
     *
     * @param tel the value for user.tel
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userlevel
     *
     * @return the value of user.userlevel
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public Integer getUserlevel() {
        return userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userlevel
     *
     * @param userlevel the value for user.userlevel
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setUserlevel(Integer userlevel) {
        this.userlevel = userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.picture
     *
     * @return the value of user.picture
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.picture
     *
     * @param picture the value for user.picture
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.idarea
     *
     * @return the value of user.idarea
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public Integer getIdarea() {
        return idarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.idarea
     *
     * @param idarea the value for user.idarea
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setIdarea(Integer idarea) {
        this.idarea = idarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.idgrade
     *
     * @return the value of user.idgrade
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public Integer getIdgrade() {
        return idgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.idgrade
     *
     * @param idgrade the value for user.idgrade
     *
     * @mbggenerated Sun Mar 25 11:47:40 CST 2018
     */
    public void setIdgrade(Integer idgrade) {
        this.idgrade = idgrade;
    }
}