package entity;

public class Usertoindex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertoindex.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertoindex.iduser
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertoindex.idindexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    private Integer idindexes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertoindex.id
     *
     * @return the value of usertoindex.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertoindex.id
     *
     * @param id the value for usertoindex.id
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertoindex.iduser
     *
     * @return the value of usertoindex.iduser
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertoindex.iduser
     *
     * @param iduser the value for usertoindex.iduser
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertoindex.idindexes
     *
     * @return the value of usertoindex.idindexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public Integer getIdindexes() {
        return idindexes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertoindex.idindexes
     *
     * @param idindexes the value for usertoindex.idindexes
     *
     * @mbggenerated Sun Mar 25 09:09:51 CST 2018
     */
    public void setIdindexes(Integer idindexes) {
        this.idindexes = idindexes;
    }
}